--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Vecnavium/VecxLeaderboards
build-by-default: true
branches:
- main
projects:
  VecxLeaderboards:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^2.0.0
...
