name: VecnaLeaderboards
author: Vecnavium
main: Vecnavium\VecnaLeaderboards\Main
version: "1.2.1"
api: [3.0.0]
description: A Pocketmine-MP Plugin that allows you to create leaderboards and view other Players Statistics
mcpe-protocol: [431, 440]

permissions:
  vecnaleaderboards.lb:
    default: op
    description: "Permission to create Leaderboard"
