name: VecxLeaderboards
author: Vecnavium
main: Vecnavium\VecxLeaderboards\Main
version: "1.2.0"
api: [3.0.0]
description: A Pocketmine-MP Plugin that keeps track of Player Statistics
mcpe-protocol: [431, 440]

permissions:
  vecxLeaderboards.lb:
    default: op
    description: "Permission to create Leaderboard"
