name: VecnaLeaderboards
author: Vecnavium
main: Vecnavium\VecnaLeaderboards\Main
version: "1.2.8"
api: [3.0.0]
load: POSTWORLD
description: A Pocketmine-MP Plugin that allows you to create leaderboards and view other Players Statistics. 
softdepend: [EconomyAPI]

permissions:
  vecnaleaderboards.lb:
    default: op
    description: "Permission to create Leaderboard"
